//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by HDNetVideoClient.rc
//
#define IDC_BTN_MODIFY                  3
#define IDC_SEARCH                      3
#define IDD_HDNETVIDEOCLIENT_DIALOG     102
#define IDR_MAINFRAME                   128
#define IDD_MODULE_MONITOR              129
#define IDD_LOGIN                       130
#define IDD_MODULE_CONFIG               131
#define IDD_MML_DEVICES                 132
#define IDD_MMLO_VIDEO_PARAM            133
#define IDD_MMLD_TREE                   134
#define IDD_MMLD_GROUP                  135
#define IDD_MMLO_PTZ                    136
#define IDD_MMLO_PRESET                 137
#define IDD_MMLO_CRUISE                 138
#define IDD_MML_OPERATE                 139
#define IDD_MM_LEFT                     140
#define IDD_MODI_PWD                    141
#define IDD_MM_RIGHT                    142
#define IDD_MMR_TOOL                    143
#define IDD_MMR_LIST                    144
#define IDD_MC_DEVICE                   145
#define IDD_MC_USER                     146
#define IDD_MC_LOCAL                    147
#define IDR_MENU_CONF_DEVI              148
#define IDD_MCD_ADD_AREA                149
#define IDD_MCD_ADD_ENCODER             150
#define IDD_MCD_MODIFY_CAMERA           151
#define IDB_MAIN_TOP_BACK               152
#define IDD_MML_PLAY                    152
#define IDB_BTN_MONITOR                 153
#define IDB_BTN_MONITOR2                154
#define IDB_BTN_CONFIG1                 155
#define IDB_BTN_CONFIG2                 156
#define IDB_BTN_LOG3                    157
#define IDB_BTN_LOG1                    158
#define IDB_BTN_LOG2                    159
#define IDB_BTN_CONFIG3                 160
#define IDB_BTN_MONITOR3                161
#define IDB_TAB_BACK11                  162
#define IDB_TAB_BACK12                  163
#define IDB_BTN_MONITOR3_EN             165
#define IDB_BTN_CONFIG1_EN              166
#define IDB_BTN_CONFIG2_EN              167
#define IDB_BTN_CONFIG3_EN              168
#define IDB_BTN_LOG1_EN                 169
#define IDB_BTN_LOG2_EN                 170
#define IDB_BTN_LOG3_EN                 171
#define IDB_BTN_MONITOR1_EN             172
#define IDB_BTN_MONITOR2_EN             173
#define IDB_TAB_BACK22                  174
#define IDB_TAB_BACK21                  175
#define IDB_MWIN_TOP_BACK               176
#define IDB_BTN_01PANE                  177
#define IDB_BTN_01PANE_D                178
#define IDB_BTN_01PANE_O                179
#define IDB_BTN_04PANE                  180
#define IDB_BTN_04PANE_D                181
#define IDB_BTN_04PANE_O                182
#define IDB_BTN_06PANE                  183
#define IDB_BTN_06PANE_D                184
#define IDB_BTN_06PANE_O                185
#define IDB_BTN_09PANE                  186
#define IDB_BTN_09PANE_D                187
#define IDB_BTN_09PANE_O                188
#define IDB_BTN_10PANE                  189
#define IDB_BTN_10PANE_D                190
#define IDB_BTN_10PANE_O                191
#define IDB_BTN_13PANE                  192
#define IDB_BTN_13PANE_D                193
#define IDB_BTN_13PANE_O                194
#define IDB_BTN_64PANE_O                195
#define IDB_BTN_16PANE                  196
#define IDB_BTN_16PANE_D                197
#define IDB_BTN_16PANE_O                198
#define IDB_BTN_36PANE                  199
#define IDB_BTN_36PANE_D                200
#define IDB_BTN_36PANE_O                201
#define IDB_BTN_64PANE                  202
#define IDB_BTN_64PANE_D                203
#define IDB_BTN_FULL_D                  204
#define IDB_BTN_FULL                    205
#define IDB_BTN_FULL_O                  206
#define IDB_BTN_PREVI_D                 207
#define IDB_BTN_PREVI                   208
#define IDB_BTN_PREVI_O                 209
#define IDB_BTN_NEXT_D                  210
#define IDB_BTN_NEXT                    211
#define IDB_BTN_NEXT_O                  212
#define IDB_BTN_3DPOS1                  213
#define IDB_BTN_3DPOS2                  214
#define IDB_BTN_3DPOS3                  215
#define IDB_BTN_AS1                     216
#define IDB_BTN_AS2                     217
#define IDB_BTN_AS3                     218
#define IDB_BTN_DOWN1                   219
#define IDB_BTN_DOWN2                   220
#define IDB_BTN_DOWN3                   221
#define IDB_BTN_DOWNLEFT1               222
#define IDB_BTN_DOWNLEFT2               223
#define IDB_BTN_DOWNLEFT3               224
#define IDB_BTN_FOCALB1                 225
#define IDB_BTN_FOCALB2                 226
#define IDB_BTN_FOCALB3                 227
#define IDB_BTN_FOCALF1                 228
#define IDB_BTN_FOCALF2                 229
#define IDB_BTN_FOCALF3                 230
#define IDB_BTN_LEFT1                   231
#define IDB_BTN_LEFT2                   232
#define IDB_BTN_LEFT3                   233
#define IDB_BTN_LEFTR1                  234
#define IDB_BTN_LEFTR2                  235
#define IDB_BTN_LEFTR3                  236
#define IDB_BTN_LEFTU1                  237
#define IDB_BTN_LEFTU2                  238
#define IDB_BTN_LEFTU3                  239
#define IDB_BTN_LIGHT1                  240
#define IDB_BTN_LIGHT2                  241
#define IDB_BTN_LIGHT3                  242
#define IDB_BTN_RIGHT1                  243
#define IDB_BTN_RIGHT2                  244
#define IDB_BTN_RIGHT3                  245
#define IDB_BTN_RIGHTD1                 246
#define IDB_BTN_RIGHTD2                 247
#define IDB_BTN_RIGHTD3                 248
#define IDB_BTN_UP1                     249
#define IDB_BTN_UP2                     250
#define IDB_BTN_UP3                     251
#define IDB_BTN_UPR1                    252
#define IDB_BTN_UPR2                    253
#define IDB_BTN_UPR3                    254
#define IDB_BTN_WIPER1                  255
#define IDB_BTN_WIPER2                  256
#define IDB_BTN_WIPER3                  257
#define IDB_BTN_ZOOMIN1                 258
#define IDB_BTN_ZOOMIN2                 259
#define IDB_BTN_ZOOMIN3                 260
#define IDB_BTN_ZOOMO1                  261
#define IDB_BTN_ZOOMO2                  262
#define IDB_BTN_ZOOMO3                  263
#define IDB_BTN_3DPOS4                  264
#define IDB_BTN_AB1                     265
#define IDB_BTN_AB2                     266
#define IDB_BTN_AB3                     267
#define IDB_BTN_AB4                     268
#define IDB_BTN_AS4                     269
#define IDB_BTN_DOWN4                   270
#define IDB_BTN_DOWNLEFT4               272
#define IDB_BTN_FOCALF4                 273
#define IDB_BTN_LEFT4                   274
#define IDB_BTN_LEFTU4                  275
#define IDB_BTN_LIGHT4                  276
#define IDB_BTN_RIGHT4                  277
#define IDB_BTN_RIGHTD4                 278
#define IDB_BTN_UP4                     279
#define IDB_BTN_UPR4                    280
#define IDB_BTN_WIPER4                  281
#define IDB_BTN_ZOOMIN4                 282
#define IDB_BTN_ZOOMO4                  283
#define IDB_BTN_LEFTR4                  284
#define IDB_BTN_FOCALB4                 285
#define IDB_BTN_CAPTURE1                286
#define IDB_BTN_CAPTURE2                287
#define IDB_BTN_CAPTURE3                288
#define IDB_BTN_PLAY1                   289
#define IDB_BTN_PLAY2                   290
#define IDB_BTN_PLAY3                   291
#define IDB_BTN_STOP1                   292
#define IDB_BTN_STOP2                   293
#define IDB_BTN_STOP3                   294
#define IDB_BTN_STOPALL1                295
#define IDB_BTN_STOPALL2                296
#define IDB_BTN_STOPALL3                297
#define IDB_BTN_RECORD1                 298
#define IDB_BTN_RECORD2                 299
#define IDB_BTN_RECORD3                 300
#define IDB_BTN_SOUND1                  301
#define IDB_BTN_SOUND2                  302
#define IDB_BTN_SOUND3                  303
#define IDB_BTN_TALK1                   304
#define IDB_BTN_TALK2                   305
#define IDB_BTN_TALK3                   306
#define IDB_BTN_CALLPRESET1             307
#define IDB_BTN_CALLPRESET2             308
#define IDB_BTN_CALLPRESET3             309
#define IDB_BTN_DELPRESET1              310
#define IDB_BTN_DELPRESET2              311
#define IDB_BTN_DELPRESET3              312
#define IDB_BTN_SETPRESET1              313
#define IDB_BTN_SETPRESET2              314
#define IDB_BTN_SETPRESET3              315
#define IDB_BTN_CRUISE_STOP1            316
#define IDB_BTN_CRUISE_STOP2            317
#define IDB_BTN_CRUISE_STOP3            318
#define IDB_LBL_VPARM_TITLE             319
#define IDB_BTN_DEFAULT_VALUE1          321
#define IDB_BTN_DEFAULT_VALUE2          322
#define IDB_BTN_DEFAULT_VALUE3          323
#define IDB_BTN_CLOSEVIDEO2             324
#define IDB_BTN_CLOSEVIDEO1             325
#define IDC_BTN_MONITOR                 1000
#define IDC_BTN_MAP                     1001
#define IDC_COMBO_USER                  1001
#define IDC_BTN_CONFIG                  1002
#define IDC_EDIT_PWD                    1002
#define IDC_BTN_HELP                    1003
#define IDC_STATIC_LANGUAGE             1003
#define IDC_EDIT_AREA                   1003
#define IDC_BTN_LOG                     1004
#define IDC_CHECK_LOGIN                 1004
#define IDC_TREE_DEVICE                 1004
#define IDC_BTN_PLAYBACK                1005
#define IDC_BTN_LIST                    1005
#define IDC_BTN_PTZ                     1005
#define IDC_BTN_LEFTUP                  1005
#define IDC_BTN_GROUP                   1006
#define IDC_BTN_PRESET                  1006
#define IDC_BTN_UP                      1006
#define IDC_STATIC_VERSION              1006
#define IDC_BTN_CRUISE                  1007
#define IDC_BTN_UPRIGHT                 1007
#define IDC_BTN_CONFIG_DEVI             1007
#define IDC_BTN_LEFT                    1008
#define IDC_BTN_VPARAM                  1008
#define IDC_BTN_CONFIG_LOCAL            1008
#define IDC_BUTTON5                     1009
#define IDC_BTN_CONFIG_USER             1009
#define IDC_BTN_ADD_USER                1009
#define IDC_BTN_LEFTRIGHT               1009
#define IDC_BTN_RIGHT                   1010
#define IDC_BTN_MODI_USER               1010
#define IDC_STATIC_TITLE                1010
#define IDC_BTN_LEFTDOWN                1011
#define IDC_BTN_DEL_USER                1011
#define IDC_EDIT_NAME                   1011
#define IDC_BTN_DOWN                    1012
#define IDC_STATIC_NAME                 1012
#define IDC_BTN_RIGHTDOWN               1013
#define IDC_STATIC_UPNAME               1013
#define IDC_STATIC_NO                   1013
#define IDC_BTN_ZOOM1                   1014
#define IDC_EDIT_UP_NAME                1014
#define IDC_STATIC_PORT                 1014
#define IDC_EDIT_NO                     1014
#define IDC_BTN_ZOOM2                   1015
#define IDC_STATIC_IPMODE               1015
#define IDC_STATIC_DEVI_NAME            1015
#define IDC_BTN_FOCAL1                  1016
#define IDC_EDIT_DEVI_NAME              1016
#define IDC_BTN_FOCAL2                  1017
#define IDC_EDIT_PORT                   1017
#define IDC_STATIC_DEVI_IP              1017
#define IDC_BTN_APERT1                  1018
#define IDC_EDIT_USER                   1018
#define IDC_EDIT_DEVI_IP                1018
#define IDC_BTN_APERT2                  1019
#define IDC_COMBO_MODE                  1019
#define IDC_STATIC_STREAM               1019
#define IDC_SLIDER1                     1020
#define IDC_EDIT_CHANNEL                1020
#define IDC_SLIDER_BRIGHT               1020
#define IDC_BUTTON16                    1021
#define IDC_EDIT_ID                     1021
#define IDC_BTN_DEFAULT                 1021
#define IDC_BUTTON17                    1022
#define IDC_SLIDER2                     1022
#define IDC_IPADDRESS_MULTICAST         1022
#define IDC_BTN_START                   1022
#define IDC_SLIDER_CONTRAST             1022
#define IDC_LIST1                       1023
#define IDC_BTN_WIPER                   1023
#define IDC_SLIDER3                     1023
#define IDC_IPADDRESS_DNS               1023
#define IDC_SLIDER_SATURAT              1023
#define IDC_RADIO_CN                    1024
#define IDC_BUTTON19                    1024
#define IDC_SLIDER4                     1024
#define IDC_IPADDRESS_DEVICE            1024
#define IDC_BTN_SET_CRUISE              1024
#define IDC_SLIDER_SHARP                1024
#define IDC_RADIO_EN                    1025
#define IDC_SLIDER5                     1025
#define IDC_STATIC_IP                   1025
#define IDC_SLIDER_SOUND                1025
#define IDC_STATIC_USER                 1026
#define IDC_TITLE                       1026
#define IDC_STATIC_PWD                  1027
#define IDC_STATIC_PASSWORD             1028
#define IDC_STATIC_CHANNEL              1028
#define IDC_COMBO_STREAM                1028
#define IDC_STATIC_INFO                 1029
#define IDC_STATIC_AREA                 1029
#define IDC_STATIC_OLD                  1030
#define IDC_STATIC_ID                   1030
#define IDC_LBL_TOOL_BAR                1030
#define IDC_EDIT_OLD                    1031
#define IDC_STATIC_DNS                  1031
#define IDC_STATIC_BACK                 1031
#define IDC_STATIC_NEW                  1032
#define IDC_STATIC_MULTICAST            1032
#define IDC_BTN_PANE1                   1032
#define IDC_EDIT_NEW                    1033
#define IDC_BTN_PANE4                   1033
#define IDC_STATIC_VALUE                1033
#define IDC_STATIC_NEW2                 1034
#define IDC_BTN_PANE6                   1034
#define IDC_BTN_PLAY                    1034
#define IDC_EDIT_NEW2                   1035
#define IDC_BTN_PANE9                   1035
#define IDC_BTN_RECORD                  1035
#define IDC_LIST_PRESET                 1035
#define IDC_BTN_OK                      1036
#define IDC_BTN_PANE10                  1036
#define IDC_BTN_CAPTURE                 1036
#define IDC_BTN_PRESET_CALL             1036
#define IDC_SLIDER_PTZ                  1037
#define IDC_BTN_PANE13                  1037
#define IDC_BTN_SOUND                   1037
#define IDC_BTN_PRESET_SET              1037
#define IDC_BTN_LIGHT                   1038
#define IDC_BTN_PANE16                  1038
#define IDC_BTN_TALK                    1038
#define IDC_BTN_PRESET_DEL              1038
#define IDC_BTN_3D                      1039
#define IDC_BTN_PANE36                  1039
#define IDC_BTN_STOP                    1039
#define IDC_LIST_CRUISE                 1039
#define IDC_BTN_PANE64                  1040
#define IDC_BTN_STOPALL                 1040
#define IDC_BTN_STOP_CRUI               1040
#define IDC_BTN_FULLSCREEN              1041
#define IDC_STATIC_BRIGHT               1041
#define IDC_BTN_PREVI                   1042
#define IDC_STATIC_CONTRAST             1042
#define IDC_LIST_ALARM                  1042
#define IDC_BTN_NEXT                    1043
#define IDC_STATIC_SATURAT              1043
#define IDC_STATIC_SHARP                1044
#define IDC_STATIC_SOUND                1045
#define IDM_CD_ADD_AREA                 32771
#define IDM_CD_ADD_DEVICE               32772
#define IDM_CD_DEL_NODE                 32773

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        326
#define _APS_NEXT_COMMAND_VALUE         32774
#define _APS_NEXT_CONTROL_VALUE         1043
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
